// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGVGX7Guqw38FsOniB2uLoqwx-oU79m0c',
    appId: '1:916588778959:web:be70b150564767159deeba',
    messagingSenderId: '916588778959',
    projectId: 'flutter-dataone-proje',
    authDomain: 'flutter-dataone-proje.firebaseapp.com',
    storageBucket: 'flutter-dataone-proje.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdGE8Xcj_mxeDjlEGotr3rCpeS12LWYM',
    appId: '1:916588778959:android:8581cb33abe897c79deeba',
    messagingSenderId: '916588778959',
    projectId: 'flutter-dataone-proje',
    storageBucket: 'flutter-dataone-proje.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtLIuugK3hKItX9CkUavP8Mq21D517rbI',
    appId: '1:916588778959:ios:dfe63ce52003787d9deeba',
    messagingSenderId: '916588778959',
    projectId: 'flutter-dataone-proje',
    storageBucket: 'flutter-dataone-proje.appspot.com',
    iosClientId: '916588778959-sugm16te384aemigu3nqmf9l9snludg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterData1',
  );
}
